name: build_master
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  





dev_dependencies:
  flutter_test:
    sdk: flutter
  


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/signin_background.png
    - assets/images/ai_buddy.png
    - assets/images/home_background.png
    - assets/images/ai_camera_icon.png
    - assets/images/image_upload_icon.png
    - assets/images/build_master.png
    - assets/images/home_icon_highlighted.png
    - assets/images/home_icon_not_highlighted.png
    - assets/images/forum_icon_highlighted.png
    - assets/images/forum_icon_not_highlighted.png
    - assets/images/my_build_icon_not_highlighted.png
    - assets/images/my_build_icon_highlighted.png
    - assets/images/profile_icon_highlighted_no_image.png
    - assets/images/profile_icon_not_highlighted_no_image.png
    - assets/parts/cpu.json
    - assets/parts/gpu.json
    - assets/parts/ram.json
    - assets/parts/hdd.json
    - assets/parts/ssd.json
    - assets/parts/motherboard.json
    - assets/images/part_icons.png
    - assets/icons/rocket_launch.svg
    - assets/images/ai_icon.png
    - assets/images/forum_background.png
    - assets/labels.txt
    - assets/model_unquant.tflite
    - assets/images/home_screen.png
    - assets/images/forum_screen.png
    - assets/images/my_builds_screen.png
    - assets/images/profile_screen.png
    - assets/images/profile.png
    - assets/images/default_profile_image.png


 